FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16 AS builder

WORKDIR /build
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.16:base-rhel9

LABEL io.openshift.release.operator=true
LABEL description="KubeVirt Cloud Controller Manager"

COPY --from=builder /build/bin/kubevirt-cloud-controller-manager /bin/kubevirt-cloud-controller-manager

ENTRYPOINT [ "/bin/kubevirt-cloud-controller-manager" ]
