FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14 AS builder

WORKDIR /build
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.14:base

LABEL io.openshift.release.operator=true
LABEL description="KubeVirt Cloud Controller Manager"

COPY --from=builder /build/bin/kubevirt-cloud-controller-manager /bin/kubevirt-cloud-controller-manager

ENTRYPOINT [ "/bin/kubevirt-cloud-controller-manager" ]
